{% set name = "proto-opentelemetry-proto" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/open-telemetry/opentelemetry-proto/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 92682778affe8d00cd36f68308b49295db34fce379bef0a781c50837eccbc3c0

build:
  noarch: generic
  number: 0

requirements:
  build:
  host:
  run:

test:
  commands:
    - test -f $PREFIX/share/opentelemetry/opentelemetry-proto/LICENSE  # [unix]
    - test -f $PREFIX/share/opentelemetry/opentelemetry-proto/opentelemetry/proto/common/v1/common.proto  # [unix]
    - if not exist %PREFIX%\Library\share\opentelemetry\opentelemetry-proto\LICENSE exit 1  # [win]
    - if not exist %PREFIX%\Library\share\opentelemetry\opentelemetry-proto\opentelemetry\proto\common\v1\common.proto exit 1  # [win]

about:
  home: https://github.com/open-telemetry/opentelemetry-proto
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Protobuf definitions for the OpenTelemetry protocol (OTLP)
  description: |
    OpenTelemetry is a collection of tools, APIs, and SDKs. Use it to
    instrument, generate, collect, and export telemetry data (metrics,
    logs, and traces) to help you analyze your software’s performance
    and behavior.
  doc_url: https://github.com/open-telemetry/opentelemetry-proto
  dev_url: https://opentelemetry.io/docs/reference/specification/

extra:
  recipe-maintainers:
    - lidavidm
